name: NPCTrade
version: 1.0
main: net.andrasia.kiryu144.npctrade.NPCTrade
description: NPCTrade by Kiryu144
author: Kiryu144
api-version: 1.13
depend: [Citizens, Vault, KiryuLib]
commands:
  tradenpc:
    usage: /<command>
    description: NPCTrade